apiVersion: v1
kind: Namespace
metadata:
  name: vllm
  labels:
    app.kubernetes.io/managed-by: kubectl
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    app.kubernetes.io/managed-by: helm
